# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.6.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLabel,
    QLayout, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSpacerItem, QStatusBar,
    QToolBar, QVBoxLayout, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(706, 556)
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionClearImage = QAction(MainWindow)
        self.actionClearImage.setObjectName(u"actionClearImage")
        self.actionOpenImage = QAction(MainWindow)
        self.actionOpenImage.setObjectName(u"actionOpenImage")
        icon = QIcon()
        icon.addFile(u":/icons/blue-folder-open-image.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpenImage.setIcon(icon)
        self.actionSaveImage = QAction(MainWindow)
        self.actionSaveImage.setObjectName(u"actionSaveImage")
        icon1 = QIcon()
        icon1.addFile(u":/icons/disk.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSaveImage.setIcon(icon1)
        self.actionInvertColors = QAction(MainWindow)
        self.actionInvertColors.setObjectName(u"actionInvertColors")
        self.actionFlipHorizontal = QAction(MainWindow)
        self.actionFlipHorizontal.setObjectName(u"actionFlipHorizontal")
        self.actionFlipVertical = QAction(MainWindow)
        self.actionFlipVertical.setObjectName(u"actionFlipVertical")
        self.actionNewImage = QAction(MainWindow)
        self.actionNewImage.setObjectName(u"actionNewImage")
        icon2 = QIcon()
        icon2.addFile(u":/icons/document-image.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNewImage.setIcon(icon2)
        self.actionBold = QAction(MainWindow)
        self.actionBold.setObjectName(u"actionBold")
        self.actionBold.setCheckable(True)
        icon3 = QIcon()
        icon3.addFile(u":/icons/edit-bold.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBold.setIcon(icon3)
        self.actionItalic = QAction(MainWindow)
        self.actionItalic.setObjectName(u"actionItalic")
        self.actionItalic.setCheckable(True)
        icon4 = QIcon()
        icon4.addFile(u":/icons/edit-italic.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionItalic.setIcon(icon4)
        self.actionUnderline = QAction(MainWindow)
        self.actionUnderline.setObjectName(u"actionUnderline")
        self.actionUnderline.setCheckable(True)
        icon5 = QIcon()
        icon5.addFile(u":/icons/edit-underline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUnderline.setIcon(icon5)
        self.actionFillShapes = QAction(MainWindow)
        self.actionFillShapes.setObjectName(u"actionFillShapes")
        self.actionFillShapes.setCheckable(True)
        icon6 = QIcon()
        icon6.addFile(u":/icons/paint-can-color.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFillShapes.setIcon(icon6)
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.centralWidget)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.verticalLayout_2 = QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.widget = QWidget(self.centralWidget)
        self.widget.setObjectName(u"widget")
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.gridLayout = QGridLayout(self.widget)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setObjectName(u"gridLayout")
        self.rectButton = QPushButton(self.widget)
        self.rectButton.setObjectName(u"rectButton")
        self.rectButton.setMinimumSize(QSize(30, 30))
        self.rectButton.setMaximumSize(QSize(30, 30))
        icon7 = QIcon()
        icon7.addFile(u":/icons/layer-shape.png", QSize(), QIcon.Normal, QIcon.Off)
        self.rectButton.setIcon(icon7)
        self.rectButton.setCheckable(True)

        self.gridLayout.addWidget(self.rectButton, 6, 0, 1, 1)

        self.polylineButton = QPushButton(self.widget)
        self.polylineButton.setObjectName(u"polylineButton")
        self.polylineButton.setMinimumSize(QSize(30, 30))
        self.polylineButton.setMaximumSize(QSize(30, 30))
        icon8 = QIcon()
        icon8.addFile(u":/icons/layer-shape-polyline.png", QSize(), QIcon.Normal, QIcon.Off)
        self.polylineButton.setIcon(icon8)
        self.polylineButton.setCheckable(True)

        self.gridLayout.addWidget(self.polylineButton, 5, 1, 1, 1)

        self.selectrectButton = QPushButton(self.widget)
        self.selectrectButton.setObjectName(u"selectrectButton")
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.selectrectButton.sizePolicy().hasHeightForWidth())
        self.selectrectButton.setSizePolicy(sizePolicy1)
        self.selectrectButton.setMinimumSize(QSize(30, 30))
        self.selectrectButton.setMaximumSize(QSize(30, 30))
        icon9 = QIcon()
        icon9.addFile(u":/icons/selection.png", QSize(), QIcon.Normal, QIcon.Off)
        self.selectrectButton.setIcon(icon9)
        self.selectrectButton.setCheckable(True)

        self.gridLayout.addWidget(self.selectrectButton, 0, 1, 1, 1)

        self.eraserButton = QPushButton(self.widget)
        self.eraserButton.setObjectName(u"eraserButton")
        sizePolicy1.setHeightForWidth(self.eraserButton.sizePolicy().hasHeightForWidth())
        self.eraserButton.setSizePolicy(sizePolicy1)
        self.eraserButton.setMinimumSize(QSize(30, 30))
        self.eraserButton.setMaximumSize(QSize(30, 30))
        icon10 = QIcon()
        icon10.addFile(u":/icons/eraser.png", QSize(), QIcon.Normal, QIcon.Off)
        self.eraserButton.setIcon(icon10)
        self.eraserButton.setCheckable(True)

        self.gridLayout.addWidget(self.eraserButton, 1, 0, 1, 1)

        self.stampButton = QPushButton(self.widget)
        self.stampButton.setObjectName(u"stampButton")
        sizePolicy1.setHeightForWidth(self.stampButton.sizePolicy().hasHeightForWidth())
        self.stampButton.setSizePolicy(sizePolicy1)
        self.stampButton.setMinimumSize(QSize(30, 30))
        self.stampButton.setMaximumSize(QSize(30, 30))
        icon11 = QIcon()
        icon11.addFile(u":/icons/cake.png", QSize(), QIcon.Normal, QIcon.Off)
        self.stampButton.setIcon(icon11)
        self.stampButton.setCheckable(True)

        self.gridLayout.addWidget(self.stampButton, 2, 1, 1, 1)

        self.dropperButton = QPushButton(self.widget)
        self.dropperButton.setObjectName(u"dropperButton")
        sizePolicy1.setHeightForWidth(self.dropperButton.sizePolicy().hasHeightForWidth())
        self.dropperButton.setSizePolicy(sizePolicy1)
        self.dropperButton.setMinimumSize(QSize(30, 30))
        self.dropperButton.setMaximumSize(QSize(30, 30))
        icon12 = QIcon()
        icon12.addFile(u":/icons/pipette.png", QSize(), QIcon.Normal, QIcon.Off)
        self.dropperButton.setIcon(icon12)
        self.dropperButton.setCheckable(True)

        self.gridLayout.addWidget(self.dropperButton, 2, 0, 1, 1)

        self.selectpolyButton = QPushButton(self.widget)
        self.selectpolyButton.setObjectName(u"selectpolyButton")
        sizePolicy1.setHeightForWidth(self.selectpolyButton.sizePolicy().hasHeightForWidth())
        self.selectpolyButton.setSizePolicy(sizePolicy1)
        self.selectpolyButton.setMinimumSize(QSize(30, 30))
        self.selectpolyButton.setMaximumSize(QSize(30, 30))
        icon13 = QIcon()
        icon13.addFile(u":/icons/selection-poly.png", QSize(), QIcon.Normal, QIcon.Off)
        self.selectpolyButton.setIcon(icon13)
        self.selectpolyButton.setCheckable(True)

        self.gridLayout.addWidget(self.selectpolyButton, 0, 0, 1, 1)

        self.brushButton = QPushButton(self.widget)
        self.brushButton.setObjectName(u"brushButton")
        sizePolicy1.setHeightForWidth(self.brushButton.sizePolicy().hasHeightForWidth())
        self.brushButton.setSizePolicy(sizePolicy1)
        self.brushButton.setMinimumSize(QSize(30, 30))
        self.brushButton.setMaximumSize(QSize(30, 30))
        icon14 = QIcon()
        icon14.addFile(u":/icons/paint-brush.png", QSize(), QIcon.Normal, QIcon.Off)
        self.brushButton.setIcon(icon14)
        self.brushButton.setCheckable(True)

        self.gridLayout.addWidget(self.brushButton, 3, 1, 1, 1)

        self.penButton = QPushButton(self.widget)
        self.penButton.setObjectName(u"penButton")
        sizePolicy1.setHeightForWidth(self.penButton.sizePolicy().hasHeightForWidth())
        self.penButton.setSizePolicy(sizePolicy1)
        self.penButton.setMinimumSize(QSize(30, 30))
        self.penButton.setMaximumSize(QSize(30, 30))
        icon15 = QIcon()
        icon15.addFile(u":/icons/pencil.png", QSize(), QIcon.Normal, QIcon.Off)
        self.penButton.setIcon(icon15)
        self.penButton.setCheckable(True)

        self.gridLayout.addWidget(self.penButton, 3, 0, 1, 1)

        self.fillButton = QPushButton(self.widget)
        self.fillButton.setObjectName(u"fillButton")
        sizePolicy1.setHeightForWidth(self.fillButton.sizePolicy().hasHeightForWidth())
        self.fillButton.setSizePolicy(sizePolicy1)
        self.fillButton.setMinimumSize(QSize(30, 30))
        self.fillButton.setMaximumSize(QSize(30, 30))
        icon16 = QIcon()
        icon16.addFile(u":/icons/paint-can.png", QSize(), QIcon.Normal, QIcon.Off)
        self.fillButton.setIcon(icon16)
        self.fillButton.setCheckable(True)

        self.gridLayout.addWidget(self.fillButton, 1, 1, 1, 1)

        self.textButton = QPushButton(self.widget)
        self.textButton.setObjectName(u"textButton")
        sizePolicy1.setHeightForWidth(self.textButton.sizePolicy().hasHeightForWidth())
        self.textButton.setSizePolicy(sizePolicy1)
        self.textButton.setMinimumSize(QSize(30, 30))
        self.textButton.setMaximumSize(QSize(30, 30))
        icon17 = QIcon()
        icon17.addFile(u":/icons/edit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.textButton.setIcon(icon17)
        self.textButton.setCheckable(True)

        self.gridLayout.addWidget(self.textButton, 4, 1, 1, 1)

        self.polygonButton = QPushButton(self.widget)
        self.polygonButton.setObjectName(u"polygonButton")
        self.polygonButton.setMinimumSize(QSize(30, 30))
        self.polygonButton.setMaximumSize(QSize(30, 30))
        icon18 = QIcon()
        icon18.addFile(u":/icons/layer-shape-polygon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.polygonButton.setIcon(icon18)
        self.polygonButton.setCheckable(True)

        self.gridLayout.addWidget(self.polygonButton, 6, 1, 1, 1)

        self.roundrectButton = QPushButton(self.widget)
        self.roundrectButton.setObjectName(u"roundrectButton")
        self.roundrectButton.setMinimumSize(QSize(30, 30))
        self.roundrectButton.setMaximumSize(QSize(30, 30))
        icon19 = QIcon()
        icon19.addFile(u":/icons/layer-shape-round.png", QSize(), QIcon.Normal, QIcon.Off)
        self.roundrectButton.setIcon(icon19)
        self.roundrectButton.setCheckable(True)

        self.gridLayout.addWidget(self.roundrectButton, 7, 1, 1, 1)

        self.ellipseButton = QPushButton(self.widget)
        self.ellipseButton.setObjectName(u"ellipseButton")
        self.ellipseButton.setMinimumSize(QSize(30, 30))
        self.ellipseButton.setMaximumSize(QSize(30, 30))
        icon20 = QIcon()
        icon20.addFile(u":/icons/layer-shape-ellipse.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ellipseButton.setIcon(icon20)
        self.ellipseButton.setCheckable(True)

        self.gridLayout.addWidget(self.ellipseButton, 7, 0, 1, 1)

        self.lineButton = QPushButton(self.widget)
        self.lineButton.setObjectName(u"lineButton")
        self.lineButton.setMinimumSize(QSize(30, 30))
        self.lineButton.setMaximumSize(QSize(30, 30))
        icon21 = QIcon()
        icon21.addFile(u":/icons/layer-shape-line.png", QSize(), QIcon.Normal, QIcon.Off)
        self.lineButton.setIcon(icon21)
        self.lineButton.setCheckable(True)

        self.gridLayout.addWidget(self.lineButton, 5, 0, 1, 1)

        self.sprayButton = QPushButton(self.widget)
        self.sprayButton.setObjectName(u"sprayButton")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.sprayButton.sizePolicy().hasHeightForWidth())
        self.sprayButton.setSizePolicy(sizePolicy2)
        self.sprayButton.setMinimumSize(QSize(30, 30))
        self.sprayButton.setMaximumSize(QSize(30, 30))
        icon22 = QIcon()
        icon22.addFile(u":/icons/spray.png", QSize(), QIcon.Normal, QIcon.Off)
        self.sprayButton.setIcon(icon22)
        self.sprayButton.setCheckable(True)
        self.sprayButton.setFlat(False)

        self.gridLayout.addWidget(self.sprayButton, 4, 0, 1, 1)


        self.verticalLayout_2.addWidget(self.widget)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.verticalLayout_2.addItem(self.verticalSpacer)


        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.canvas = QLabel(self.centralWidget)
        self.canvas.setObjectName(u"canvas")
        sizePolicy3 = QSizePolicy(QSizePolicy.MinimumExpanding, QSizePolicy.MinimumExpanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.canvas.sizePolicy().hasHeightForWidth())
        self.canvas.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.canvas)


        self.verticalLayout.addLayout(self.horizontalLayout)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.widget_3 = QWidget(self.centralWidget)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setMinimumSize(QSize(78, 0))
        self.widget_3.setMaximumSize(QSize(78, 16777215))
        self.secondaryButton = QPushButton(self.widget_3)
        self.secondaryButton.setObjectName(u"secondaryButton")
        self.secondaryButton.setGeometry(QRect(30, 10, 40, 40))
        self.secondaryButton.setMinimumSize(QSize(40, 40))
        self.secondaryButton.setMaximumSize(QSize(40, 40))
        self.primaryButton = QPushButton(self.widget_3)
        self.primaryButton.setObjectName(u"primaryButton")
        self.primaryButton.setGeometry(QRect(10, 0, 40, 40))
        self.primaryButton.setMinimumSize(QSize(40, 40))
        self.primaryButton.setMaximumSize(QSize(40, 40))

        self.horizontalLayout_2.addWidget(self.widget_3)

        self.widget_2 = QWidget(self.centralWidget)
        self.widget_2.setObjectName(u"widget_2")
        self.gridLayout_2 = QGridLayout(self.widget_2)
        self.gridLayout_2.setSpacing(15)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(15, 0, 15, 15)
        self.colorButton_11 = QPushButton(self.widget_2)
        self.colorButton_11.setObjectName(u"colorButton_11")
        sizePolicy1.setHeightForWidth(self.colorButton_11.sizePolicy().hasHeightForWidth())
        self.colorButton_11.setSizePolicy(sizePolicy1)
        self.colorButton_11.setMinimumSize(QSize(20, 20))
        self.colorButton_11.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_11, 0, 10, 1, 1)

        self.colorButton_7 = QPushButton(self.widget_2)
        self.colorButton_7.setObjectName(u"colorButton_7")
        sizePolicy1.setHeightForWidth(self.colorButton_7.sizePolicy().hasHeightForWidth())
        self.colorButton_7.setSizePolicy(sizePolicy1)
        self.colorButton_7.setMinimumSize(QSize(20, 20))
        self.colorButton_7.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_7, 0, 6, 1, 1)

        self.colorButton_9 = QPushButton(self.widget_2)
        self.colorButton_9.setObjectName(u"colorButton_9")
        sizePolicy1.setHeightForWidth(self.colorButton_9.sizePolicy().hasHeightForWidth())
        self.colorButton_9.setSizePolicy(sizePolicy1)
        self.colorButton_9.setMinimumSize(QSize(20, 20))
        self.colorButton_9.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_9, 0, 8, 1, 1)

        self.colorButton_10 = QPushButton(self.widget_2)
        self.colorButton_10.setObjectName(u"colorButton_10")
        sizePolicy1.setHeightForWidth(self.colorButton_10.sizePolicy().hasHeightForWidth())
        self.colorButton_10.setSizePolicy(sizePolicy1)
        self.colorButton_10.setMinimumSize(QSize(20, 20))
        self.colorButton_10.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_10, 0, 9, 1, 1)

        self.colorButton_23 = QPushButton(self.widget_2)
        self.colorButton_23.setObjectName(u"colorButton_23")
        sizePolicy1.setHeightForWidth(self.colorButton_23.sizePolicy().hasHeightForWidth())
        self.colorButton_23.setSizePolicy(sizePolicy1)
        self.colorButton_23.setMinimumSize(QSize(20, 20))
        self.colorButton_23.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_23, 1, 8, 1, 1)

        self.colorButton_18 = QPushButton(self.widget_2)
        self.colorButton_18.setObjectName(u"colorButton_18")
        sizePolicy1.setHeightForWidth(self.colorButton_18.sizePolicy().hasHeightForWidth())
        self.colorButton_18.setSizePolicy(sizePolicy1)
        self.colorButton_18.setMinimumSize(QSize(20, 20))
        self.colorButton_18.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_18, 1, 3, 1, 1)

        self.colorButton_20 = QPushButton(self.widget_2)
        self.colorButton_20.setObjectName(u"colorButton_20")
        sizePolicy1.setHeightForWidth(self.colorButton_20.sizePolicy().hasHeightForWidth())
        self.colorButton_20.setSizePolicy(sizePolicy1)
        self.colorButton_20.setMinimumSize(QSize(20, 20))
        self.colorButton_20.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_20, 1, 5, 1, 1)

        self.colorButton_6 = QPushButton(self.widget_2)
        self.colorButton_6.setObjectName(u"colorButton_6")
        sizePolicy1.setHeightForWidth(self.colorButton_6.sizePolicy().hasHeightForWidth())
        self.colorButton_6.setSizePolicy(sizePolicy1)
        self.colorButton_6.setMinimumSize(QSize(20, 20))
        self.colorButton_6.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_6, 0, 5, 1, 1)

        self.colorButton_3 = QPushButton(self.widget_2)
        self.colorButton_3.setObjectName(u"colorButton_3")
        sizePolicy1.setHeightForWidth(self.colorButton_3.sizePolicy().hasHeightForWidth())
        self.colorButton_3.setSizePolicy(sizePolicy1)
        self.colorButton_3.setMinimumSize(QSize(20, 20))
        self.colorButton_3.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_3, 0, 2, 1, 1)

        self.colorButton_24 = QPushButton(self.widget_2)
        self.colorButton_24.setObjectName(u"colorButton_24")
        sizePolicy1.setHeightForWidth(self.colorButton_24.sizePolicy().hasHeightForWidth())
        self.colorButton_24.setSizePolicy(sizePolicy1)
        self.colorButton_24.setMinimumSize(QSize(20, 20))
        self.colorButton_24.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_24, 1, 9, 1, 1)

        self.colorButton_17 = QPushButton(self.widget_2)
        self.colorButton_17.setObjectName(u"colorButton_17")
        sizePolicy1.setHeightForWidth(self.colorButton_17.sizePolicy().hasHeightForWidth())
        self.colorButton_17.setSizePolicy(sizePolicy1)
        self.colorButton_17.setMinimumSize(QSize(20, 20))
        self.colorButton_17.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_17, 1, 2, 1, 1)

        self.colorButton_1 = QPushButton(self.widget_2)
        self.colorButton_1.setObjectName(u"colorButton_1")
        sizePolicy1.setHeightForWidth(self.colorButton_1.sizePolicy().hasHeightForWidth())
        self.colorButton_1.setSizePolicy(sizePolicy1)
        self.colorButton_1.setMinimumSize(QSize(20, 20))
        self.colorButton_1.setMaximumSize(QSize(20, 13))
        self.colorButton_1.setStyleSheet(u"")

        self.gridLayout_2.addWidget(self.colorButton_1, 0, 0, 1, 1)

        self.colorButton_8 = QPushButton(self.widget_2)
        self.colorButton_8.setObjectName(u"colorButton_8")
        sizePolicy1.setHeightForWidth(self.colorButton_8.sizePolicy().hasHeightForWidth())
        self.colorButton_8.setSizePolicy(sizePolicy1)
        self.colorButton_8.setMinimumSize(QSize(20, 20))
        self.colorButton_8.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_8, 0, 7, 1, 1)

        self.colorButton_27 = QPushButton(self.widget_2)
        self.colorButton_27.setObjectName(u"colorButton_27")
        sizePolicy1.setHeightForWidth(self.colorButton_27.sizePolicy().hasHeightForWidth())
        self.colorButton_27.setSizePolicy(sizePolicy1)
        self.colorButton_27.setMinimumSize(QSize(20, 20))
        self.colorButton_27.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_27, 1, 12, 1, 1)

        self.colorButton_22 = QPushButton(self.widget_2)
        self.colorButton_22.setObjectName(u"colorButton_22")
        sizePolicy1.setHeightForWidth(self.colorButton_22.sizePolicy().hasHeightForWidth())
        self.colorButton_22.setSizePolicy(sizePolicy1)
        self.colorButton_22.setMinimumSize(QSize(20, 20))
        self.colorButton_22.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_22, 1, 7, 1, 1)

        self.colorButton_15 = QPushButton(self.widget_2)
        self.colorButton_15.setObjectName(u"colorButton_15")
        sizePolicy1.setHeightForWidth(self.colorButton_15.sizePolicy().hasHeightForWidth())
        self.colorButton_15.setSizePolicy(sizePolicy1)
        self.colorButton_15.setMinimumSize(QSize(20, 20))
        self.colorButton_15.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_15, 1, 0, 1, 1)

        self.colorButton_5 = QPushButton(self.widget_2)
        self.colorButton_5.setObjectName(u"colorButton_5")
        sizePolicy1.setHeightForWidth(self.colorButton_5.sizePolicy().hasHeightForWidth())
        self.colorButton_5.setSizePolicy(sizePolicy1)
        self.colorButton_5.setMinimumSize(QSize(20, 20))
        self.colorButton_5.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_5, 0, 4, 1, 1)

        self.colorButton_2 = QPushButton(self.widget_2)
        self.colorButton_2.setObjectName(u"colorButton_2")
        sizePolicy1.setHeightForWidth(self.colorButton_2.sizePolicy().hasHeightForWidth())
        self.colorButton_2.setSizePolicy(sizePolicy1)
        self.colorButton_2.setMinimumSize(QSize(20, 20))
        self.colorButton_2.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_2, 0, 1, 1, 1)

        self.colorButton_16 = QPushButton(self.widget_2)
        self.colorButton_16.setObjectName(u"colorButton_16")
        sizePolicy1.setHeightForWidth(self.colorButton_16.sizePolicy().hasHeightForWidth())
        self.colorButton_16.setSizePolicy(sizePolicy1)
        self.colorButton_16.setMinimumSize(QSize(20, 20))
        self.colorButton_16.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_16, 1, 1, 1, 1)

        self.colorButton_14 = QPushButton(self.widget_2)
        self.colorButton_14.setObjectName(u"colorButton_14")
        sizePolicy1.setHeightForWidth(self.colorButton_14.sizePolicy().hasHeightForWidth())
        self.colorButton_14.setSizePolicy(sizePolicy1)
        self.colorButton_14.setMinimumSize(QSize(20, 20))
        self.colorButton_14.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_14, 0, 13, 1, 1)

        self.colorButton_4 = QPushButton(self.widget_2)
        self.colorButton_4.setObjectName(u"colorButton_4")
        sizePolicy1.setHeightForWidth(self.colorButton_4.sizePolicy().hasHeightForWidth())
        self.colorButton_4.setSizePolicy(sizePolicy1)
        self.colorButton_4.setMinimumSize(QSize(20, 20))
        self.colorButton_4.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_4, 0, 3, 1, 1)

        self.colorButton_21 = QPushButton(self.widget_2)
        self.colorButton_21.setObjectName(u"colorButton_21")
        sizePolicy1.setHeightForWidth(self.colorButton_21.sizePolicy().hasHeightForWidth())
        self.colorButton_21.setSizePolicy(sizePolicy1)
        self.colorButton_21.setMinimumSize(QSize(20, 20))
        self.colorButton_21.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_21, 1, 6, 1, 1)

        self.colorButton_25 = QPushButton(self.widget_2)
        self.colorButton_25.setObjectName(u"colorButton_25")
        sizePolicy1.setHeightForWidth(self.colorButton_25.sizePolicy().hasHeightForWidth())
        self.colorButton_25.setSizePolicy(sizePolicy1)
        self.colorButton_25.setMinimumSize(QSize(20, 20))
        self.colorButton_25.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_25, 1, 10, 1, 1)

        self.colorButton_12 = QPushButton(self.widget_2)
        self.colorButton_12.setObjectName(u"colorButton_12")
        sizePolicy1.setHeightForWidth(self.colorButton_12.sizePolicy().hasHeightForWidth())
        self.colorButton_12.setSizePolicy(sizePolicy1)
        self.colorButton_12.setMinimumSize(QSize(20, 20))
        self.colorButton_12.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_12, 0, 11, 1, 1)

        self.colorButton_19 = QPushButton(self.widget_2)
        self.colorButton_19.setObjectName(u"colorButton_19")
        sizePolicy1.setHeightForWidth(self.colorButton_19.sizePolicy().hasHeightForWidth())
        self.colorButton_19.setSizePolicy(sizePolicy1)
        self.colorButton_19.setMinimumSize(QSize(20, 20))
        self.colorButton_19.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_19, 1, 4, 1, 1)

        self.colorButton_13 = QPushButton(self.widget_2)
        self.colorButton_13.setObjectName(u"colorButton_13")
        sizePolicy1.setHeightForWidth(self.colorButton_13.sizePolicy().hasHeightForWidth())
        self.colorButton_13.setSizePolicy(sizePolicy1)
        self.colorButton_13.setMinimumSize(QSize(20, 20))
        self.colorButton_13.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_13, 0, 12, 1, 1)

        self.colorButton_26 = QPushButton(self.widget_2)
        self.colorButton_26.setObjectName(u"colorButton_26")
        sizePolicy1.setHeightForWidth(self.colorButton_26.sizePolicy().hasHeightForWidth())
        self.colorButton_26.setSizePolicy(sizePolicy1)
        self.colorButton_26.setMinimumSize(QSize(20, 20))
        self.colorButton_26.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_26, 1, 11, 1, 1)

        self.colorButton_28 = QPushButton(self.widget_2)
        self.colorButton_28.setObjectName(u"colorButton_28")
        sizePolicy1.setHeightForWidth(self.colorButton_28.sizePolicy().hasHeightForWidth())
        self.colorButton_28.setSizePolicy(sizePolicy1)
        self.colorButton_28.setMinimumSize(QSize(20, 20))
        self.colorButton_28.setMaximumSize(QSize(20, 13))

        self.gridLayout_2.addWidget(self.colorButton_28, 1, 13, 1, 1)


        self.horizontalLayout_2.addWidget(self.widget_2)

        self.stampnextButton = QPushButton(self.centralWidget)
        self.stampnextButton.setObjectName(u"stampnextButton")
        self.stampnextButton.setMinimumSize(QSize(78, 55))
        self.stampnextButton.setMaximumSize(QSize(78, 55))
        self.stampnextButton.setIconSize(QSize(80, 50))

        self.horizontalLayout_2.addWidget(self.stampnextButton)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayout_2.addItem(self.horizontalSpacer)


        self.verticalLayout.addLayout(self.horizontalLayout_2)

        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 706, 26))
        self.menuFIle = QMenu(self.menuBar)
        self.menuFIle.setObjectName(u"menuFIle")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuImage = QMenu(self.menuBar)
        self.menuImage.setObjectName(u"menuImage")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.fileToolbar = QToolBar(MainWindow)
        self.fileToolbar.setObjectName(u"fileToolbar")
        self.fileToolbar.setIconSize(QSize(16, 16))
        MainWindow.addToolBar(Qt.TopToolBarArea, self.fileToolbar)
        self.drawingToolbar = QToolBar(MainWindow)
        self.drawingToolbar.setObjectName(u"drawingToolbar")
        self.drawingToolbar.setIconSize(QSize(16, 16))
        MainWindow.addToolBar(Qt.TopToolBarArea, self.drawingToolbar)
        self.fontToolbar = QToolBar(MainWindow)
        self.fontToolbar.setObjectName(u"fontToolbar")
        self.fontToolbar.setIconSize(QSize(16, 16))
        MainWindow.addToolBar(Qt.TopToolBarArea, self.fontToolbar)

        self.menuBar.addAction(self.menuFIle.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuImage.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuFIle.addAction(self.actionNewImage)
        self.menuFIle.addAction(self.actionOpenImage)
        self.menuFIle.addAction(self.actionSaveImage)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClearImage)
        self.menuImage.addAction(self.actionInvertColors)
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.actionFlipHorizontal)
        self.menuImage.addAction(self.actionFlipVertical)
        self.fileToolbar.addAction(self.actionNewImage)
        self.fileToolbar.addAction(self.actionOpenImage)
        self.fileToolbar.addAction(self.actionSaveImage)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Piecasso", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionClearImage.setText(QCoreApplication.translate("MainWindow", u"Clear Image", None))
        self.actionOpenImage.setText(QCoreApplication.translate("MainWindow", u"Open Image...", None))
        self.actionSaveImage.setText(QCoreApplication.translate("MainWindow", u"Save Image As...", None))
        self.actionInvertColors.setText(QCoreApplication.translate("MainWindow", u"Invert Colors", None))
        self.actionFlipHorizontal.setText(QCoreApplication.translate("MainWindow", u"Flip Horizontal", None))
        self.actionFlipVertical.setText(QCoreApplication.translate("MainWindow", u"Flip Vertical", None))
        self.actionNewImage.setText(QCoreApplication.translate("MainWindow", u"New Image", None))
        self.actionBold.setText(QCoreApplication.translate("MainWindow", u"Bold", None))
#if QT_CONFIG(shortcut)
        self.actionBold.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.actionItalic.setText(QCoreApplication.translate("MainWindow", u"Italic", None))
#if QT_CONFIG(shortcut)
        self.actionItalic.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionUnderline.setText(QCoreApplication.translate("MainWindow", u"Underline", None))
        self.actionFillShapes.setText(QCoreApplication.translate("MainWindow", u"Fill Shapes?", None))
        self.rectButton.setText("")
        self.polylineButton.setText("")
        self.selectrectButton.setText("")
        self.eraserButton.setText("")
        self.stampButton.setText("")
        self.dropperButton.setText("")
        self.selectpolyButton.setText("")
        self.brushButton.setText("")
        self.penButton.setText("")
        self.fillButton.setText("")
        self.textButton.setText("")
        self.polygonButton.setText("")
        self.roundrectButton.setText("")
        self.ellipseButton.setText("")
        self.lineButton.setText("")
        self.sprayButton.setText("")
        self.canvas.setText("")
        self.secondaryButton.setText("")
        self.primaryButton.setText("")
        self.colorButton_11.setText("")
        self.colorButton_7.setText("")
        self.colorButton_9.setText("")
        self.colorButton_10.setText("")
        self.colorButton_23.setText("")
        self.colorButton_18.setText("")
        self.colorButton_20.setText("")
        self.colorButton_6.setText("")
        self.colorButton_3.setText("")
        self.colorButton_24.setText("")
        self.colorButton_17.setText("")
        self.colorButton_1.setText("")
        self.colorButton_8.setText("")
        self.colorButton_27.setText("")
        self.colorButton_22.setText("")
        self.colorButton_15.setText("")
        self.colorButton_5.setText("")
        self.colorButton_2.setText("")
        self.colorButton_16.setText("")
        self.colorButton_14.setText("")
        self.colorButton_4.setText("")
        self.colorButton_21.setText("")
        self.colorButton_25.setText("")
        self.colorButton_12.setText("")
        self.colorButton_19.setText("")
        self.colorButton_13.setText("")
        self.colorButton_26.setText("")
        self.colorButton_28.setText("")
        self.stampnextButton.setText("")
        self.menuFIle.setTitle(QCoreApplication.translate("MainWindow", u"FIle", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuImage.setTitle(QCoreApplication.translate("MainWindow", u"Image", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.fileToolbar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.drawingToolbar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
        self.fontToolbar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

